[package]
name = "raytracing_in_rust"
version = "0.1.0"
authors = ["Luca Corrieri"]
edition = "2018"

[dependencies]
image = { version = "0.23.14", default-features = false, features = ["bmp"] }
pbr = "1.0.4"
rand = "0.8.4"
